# Generated by Django 6.0.7 on 2026-07-27 01:39

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initially created the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='footer',
            field=models.FileField(blank=True, help_text='Footer HTML file for the published site.', null=True, upload_to='sites/footer/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_html_file_extension]),
        ),
        migrations.AddField(
            model_name='site',
            name='header',
            field=models.FileField(blank=True, help_text='Header HTML file for the published site.', null=True, upload_to='sites/header/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_html_file_extension]),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
