# Generated by Django 6.0.7 on 2026-08-27 07:21

import apps.common.upload_paths
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_siteversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.upload_paths.environment_upload_path),
        ),
        migrations.AlterField(
            model_name="site",
            name="footer",
            field=models.FileField(
                blank=True,
                help_text="Footer HTML file for the published site.",
                null=True,
                upload_to=apps.common.upload_paths.environment_upload_path,
                validators=[
                    apps.common.validators.validate_file_size,
                    apps.common.validators.validate_html_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="global_css",
            field=models.FileField(
                blank=True,
                help_text="Global CSS file for the published site.",
                null=True,
                upload_to=apps.common.upload_paths.environment_upload_path,
                validators=[
                    apps.common.validators.validate_file_size,
                    apps.common.validators.validate_css_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="header",
            field=models.FileField(
                blank=True,
                help_text="Header HTML file for the published site.",
                null=True,
                upload_to=apps.common.upload_paths.environment_upload_path,
                validators=[
                    apps.common.validators.validate_file_size,
                    apps.common.validators.validate_html_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.upload_paths.environment_upload_path),
        ),
    ]
