# Generated by Django 6.0.7 on 2026-08-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable model type for this audit row, e.g. site or page.",
                max_length=50,
            ),
        ),
    ]
