# Generated by Django 6.0.7 on 2026-08-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_auditlog_field_name_remove_auditlog_new_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='type',
        ),
    ]
