# Generated by Django 6.0.7 on 2026-08-07 12:56

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160)),
                (
                    "html_file",
                    models.FileField(
                        blank=True,
                        help_text="Published HTML source file for this page.",
                        null=True,
                        upload_to="pages/html/",
                        validators=[
                            apps.common.validators.validate_file_size,
                            apps.common.validators.validate_html_file_extension,
                        ],
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, default="", help_text="SEO meta description for this page."),
                ),
                (
                    "page_type",
                    models.CharField(
                        default="standard",
                        help_text="Type classification (e.g. standard, blog, landing).",
                        max_length=50,
                    ),
                ),
                ("is_homepage", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_enabled",
                    models.BooleanField(default=True, help_text="Only enabled pages are included in publish."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initially created the page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="sites.site"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified the page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [models.UniqueConstraint(fields=("site", "slug"), name="unique_page_slug_per_site")],
            },
        ),
    ]
