# Generated by Django 6.0.7 on 2026-07-27 01:39

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initially created the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='html_file',
            field=models.FileField(blank=True, help_text='Published HTML source file for this page.', null=True, upload_to='pages/html/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_html_file_extension]),
        ),
        migrations.AddField(
            model_name='page',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Only enabled pages are included in publish.'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='SEO meta description for this page.'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(default='standard', help_text='Type classification (e.g. standard, blog, landing).', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
