# Generated by Django 6.0.7 on 2026-07-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_created_by_page_html_file_page_is_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
    ]
