# Generated by Django 6.0.7 on 2026-08-27 07:21

import apps.common.upload_paths
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_remove_orphan_content_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="html_file",
            field=models.FileField(
                blank=True,
                help_text="Published HTML source file for this page.",
                null=True,
                upload_to=apps.common.upload_paths.environment_upload_path,
                validators=[
                    apps.common.validators.validate_file_size,
                    apps.common.validators.validate_html_file_extension,
                ],
            ),
        ),
    ]
